<?php

use Illuminate\Database\Seeder;

class TableInfoPostSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            ['cate_id'=>2,'post_name'=>'Lập trình viên PHP đứng đầy đường','post_img'=>'php.png','post_des'=>'Thật khó để đặt tiêu đề bài viết này như thế nào cho sát thực nhất, ban đầu tớ định đặt là “Lập trình viên PHP, những kẻ khờ dại” hoặc “Lập trình viên PHP - Những kẻ đáng thương”, thật khó lựa chọn tiêu đề nào để miêu tả hết số phận của những lập trình viên đang theo đuổi một ngôn ngữ củ chuối nhất: PHP.'],
            ['cate_id'=>2,'post_name'=>'Lỗi cần tránh khi viết CV xin việc lập trình viên, nhân viên IT là gì?','post_img'=>'cv-thumb.png','post_des'=>'Một trong những phần đau đầu nhất đối với dân lập trình nói riêng và nhân viên IT nói chung là viết lại CV cho từng vị trí công việc muốn ứng tuyển trong quá trình tìm việc mới. Đây có lẽ là thử thách khó khăn với dân kỹ thuật nói chung, còn khó hơn việc viết báo cáo hay viết code'],
            ['cate_id'=>2,'post_name'=>'Lập trình viên cần học những gì ?','post_img'=>'lap-trinh-vien-thumb.jpg','post_des'=>'Một trong những câu hỏi được nhiều bạn sinh viên ngành công nghệ quan tâm nhất đó là: Cần học những kiến thức gì, rèn luyện kỹ năng gì để trở thành một lập trình viên? Câu hỏi nghe có vẻ đơn giản nhưng rất khó để trả lời, lập trình là một lĩnh vực rất rộng, có hàng tá ngôn ngữ cần phải học, hàng trăm công nghệ cần nghiên cứu, và môi trường mỗi công ty lại hoàn toàn khác nhau, do đó các thanh niên vẫn cảm thấy rất mông lung.'],
            ['cate_id'=>2,'post_name'=>'Trả lời câu hỏi của bạn đọc','post_img'=>'tra-loi-cau-hoi-thumb.png','post_des'=>'Vừa rồi mình vừa có một buổi live stream trò chuyện cùng bạn đọc Lập Trình Cuộc Sống trên facebook. Một stream đặc biệt, nơi tất cả bạn đọc có thể nói chuyện với nhau thoải mái, chia sẻ những kinh nghiệm, buồn vui trong nghề. Thu hút hơn 2 nghìn lượt xem và hàng trăm bình luận, mình hiểu rằng các bạn rất quan tâm và có rất nhiều băn khoăn, nhất là các bạn sinh viên.'],
            ['cate_id'=>2,'post_name'=>'Các bước tạo một wireframe tuyệt vời','post_img'=>'wireframe.png','post_des'=>'Wireframe là bản phác thảo thô mô tả tổng quan về sản phẩm cuối cùng, việc vẽ wireframe là một bước quan trọng trong quy trình phát triển phần mềm. Wireframe giúp dễ dàng truyền đạt ý tưởng tăng hiệu quả giao tiếp giữa các thành viên trong team, từ đó giảm chi phí và thời gian cho toàn bộ dự án.'],
            ['cate_id'=>2,'post_name'=>'Làm product và làm outsource khác nhau như thế nào?','post_img'=>'thumbnail_default.png','post_des'=>'Trong ngành công nghệ thông tin có hai xu hướng rất điển hình đó là làm product và làm outsource. Vậy làm product là gì và làm outsource là gì? Đặc điểm và sự khác nhau giữa chúng như thế nào?'],
            ['cate_id'=>2,'post_name'=>'Chậm tiến độ - khi bạn không còn muốn viết code nữa','post_img'=>'thumb-lap-trinh-vien-met-moi.png','post_des'=>'Bạn không biết phải làm gì, đáng lẽ nó phải hoàn thành sớm hơn bạn nghĩ, bạn bị nhấn chìm bởi những ý nghĩ tiêu cực bao quanh, những ý nghĩ kiểu như: mình không thể làm kịp việc này trong thời gian ngắn như thế, trông mình thật thảm hại trong mắt đồng nghiệp. Bạn thất vọng, nghi ngờ chính bản thân mình.'],
            ['cate_id'=>2,'post_name'=>'5 việc làm đơn giản để khởi đầu "sự nghiệp" lập trình viên nghiêm túc','post_img'=>'thanh-cong.png','post_des'=>'Có những việc rất nhỏ, có thể làm trong vài phút, nhưng hiệu quả mang lại cực kỳ lớn mà bạn có thể làm ngay hôm nay. Cho dù bạn là một developer, bạn có kỹ năng code huyền diệu, khả năng teamwork tuyệt vời, hay bạn là sinh viên, đang dần hoàn thiện kỹ năng để trở thành lập trình viên trong tương lai. Thì những việc làm rất đơn giản sau sẽ giúp bạn có một khởi đầu tốt hơn rất nhiều.'],
            ['cate_id'=>2,'post_name'=>'Kiếm tiền bằng lập trình web như thế nào?','post_img'=>'web-money.png','post_des'=>'Lập trình web kiếm tiền có lẽ không còn xa lạ với hầu hết các lập trình viên. Thời đại chấm com rồi, nhà nhà làm web, người người làm web, đến cả cái quán bún chả đầu ngõ nhà mình cũng có web nữa. Web là cái đầu tiên người ta nghĩ đến khi xây dựng thương hiệu online trên internet, thế nên hiện tại thì lập trình viên web không bao giờ thiếu việc.'],
            ['cate_id'=>2,'post_name'=>'Viết CV xin việc như thế nào? Download mẫu CV chuẩn cho dân IT','post_img'=>'cv-thumb.png','post_des'=>'CV là bản tóm tắt thông tin nổi bật của bạn, phản ánh đầy đủ kinh nghiệm, trình độ, tính cách và các kỹ năng liên quan của bạn với vị trí đang ứng tuyển. Nói gì thì nói, đây là một yếu tố quan trọng quyết định việc bạn có gây ấn tượng và có được mời phỏng vấn hay không.'],
            ['cate_id'=>2,'post_name'=>'Lương lập trình viên mới ra trường - sự thật và ảo tưởng','post_img'=>'fly-get-money.png','post_des'=>'Hồi mới ra trường mình cũng như các bạn, tưởng rằng lương lập trình viên cao lắm, giờ thì đỡ nhiều rồi. Đến bây giờ, sau từng ấy năm làm vập mặt mà vẫn chưa đạt được một nửa con số lương khởi điểm 2000 đô mà một bạn sinh viên kia mong muốn, mình khẳng định rằng chúng ta đã và đang hi vọng quá nhiều vào môi trường làm việc sau khi ra trường.'],
            ['cate_id'=>2,'post_name'=>'Trông bạn sẽ cool hơn trong mắt nhà tuyển dụng nếu bạn có những thứ này','post_img'=>'tim-viec.png','post_des'=>'Nhà tuyển dụng dễ dàng có được những thông tin cần thiết, đọc được những bài viết trên blog, họ sẽ hiểu bạn hơn, một là họ ghét bạn, hai là họ thích bạn, từ đó bạn dễ tìm được môi trường làm việc phù hợp hơn.'],
            ['cate_id'=>2,'post_name'=>'Nghề IT, lập trình có dễ xin việc không?','post_img'=>'tim-viec.png','post_des'=>'Ngày nay, nghề IT ngày càng mở rộng và phát triển, mở ra nhiều cơ hội việc làm thu nhập cao cho người lao động do nhu cầu tuyển dụng gia tăng ở mọi khía cạnh. Tuy không phải ai cũng có thể làm giàu bằng nghề IT nhưng có một điều chắc chắn đó là số lượng công việc trong ngành vẫn không ngừng tăng lên'],
            ['cate_id'=>2,'post_name'=>'Nên học ngôn ngữ lập trình nào?','post_img'=>'ngon-ngu-lap-trinh.png','post_des'=>'Đối với các bạn mới học lập trình, lựa chọn ngôn ngữ lập trình để học là một việc rất khó khăn. Mỗi ngôn ngữ có những đặc điểm riêng, không có ngôn ngữ nào mạnh hơn ngôn ngữ nào cả. Bạn không biết ngôn ngữ nào phù hợp với mình, bài viết này sẽ giúp bạn.'],
            ['cate_id'=>2,'post_name'=>'Mình đã học lập trình như thế nào?','post_img'=>'thanh-cong.png','post_des'=>'Mình đã học lập trình như thế nào? Trong video này, mình chia sẻ về quãng thời gian đã học lập trình của mình từ thời cấp 3 đến lúc trở thành lập trình viên. Mỗi người có một con đường khác, cuộc sống không có ai giống ai cả, nhưng rồi cuối cùng chúng ta gặp nhau ở đây, tôi gặp bạn, những người có cùng niềm đam mê'],
            ['cate_id'=>2,'post_name'=>'Thế chốt lại, lập trình là làm cái gì?','post_img'=>'ngon-ngu-lap-trinh.png','post_des'=>'Chúng ta học bao nhiêu ngôn ngữ, công nghệ, những thứ quá cao siêu, để rồi quên đi mục đích ban đầu, Ngày xưa chúng ta đã học lập trình để làm cái gì?'],
            ['cate_id'=>2,'post_name'=>'Thực tập IT là làm gì? Có nên nhận lương hay không? Chuẩn bị gì cho kỳ thực tập?','post_img'=>'tra-loi-cau-hoi-thumb.png','post_des'=>'Thực tập là giai đoạn cực kỳ quan trọng với các bạn sinh viên, vậy cần chuẩn bị gì để có kỳ thực tập tốt?'],
        ];
        DB::table('info_post')->insert($data);
    }
}
